#!/bin/sh

action=$1
lockfile=".state_lock"
CAM_SERVER_PORT="10080"
CAM_OPTIONS="-ex auto -vf -hf -x 640 -y 480 -fps 5"
UI_SERVER_ADDR="0.0.0.0"
UI_SERVER_PORT="9595"
UI_SERVER_DEBUG="1"
export UI_SERVER_PORT
export UI_SERVER_ADDR
export UI_SERVER_DEBUG

if [ "$action" = "" ]; then
    action="start"
    fi

if [ "$action" = "start" ]; then
    if [ -f $lockfile ]; then
        echo "Lock file exists, is server already running? If not, delete $lockfile and retry"
    else 
        touch $lockfile
        echo "Starting camera stream..."
        mjpg_streamer -o "output_http.so -w ./www -p $(CAM_SERVER_PORT)" -i "input_raspicam.so $(CAM_OPTIONS)"&

        echo "Starting UI server..."
        ./pthserver.py &
        fi
elif [ "$action" = "stop" ]; then
    echo "Shutting down UI server..."
    pgrep pthserver | xargs kill

    echo "Shutting down camera stream..."
    pgrep mjpg_streamer | xargs kill

    rm $lockfile
elif [ "$action" = "status" ]; then
    echo "Proccess status"
    pgrep mjpg_streamer
    pgrep pthserver
else
    echo "Invalid action '$action'."
    echo "Usage: $0  start|stop|status"
    fi


