#!/bin/sh

action=$1
lockfile=".stream_lock"
if [ "$action" = "" ]; then
    action="start"
    fi

if [ "$action" = "start" ]; then
    if [ -f $lockfile ]; then
        echo "Lock file exists, is streamer already running? If not, delete $lockfile and retry"
    else 
        echo "Starting streamer"
        touch $lockfile
        mjpg_streamer -o "output_http.so -w ./www -p 10080" -i "input_raspicam.so -ex auto -vf -hf -x 640 -y 480 -fps 5"&
        fi
elif [ "$action" = "stop" ]; then
    echo "Shutting down streamer"
    pgrep mjpg_streamer | xargs kill
    rm $lockfile
elif [ "$action" = "status" ]; then
    echo "Proccess status"
    pgrep mjpg_streamer
else
    echo "Invalid action '$action'."
    echo "Usage: $0  start|stop|status"
    fi


